//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrakHound_Dashboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<TrakHound.Plugins.Client.PluginConfiguration> Plugin_Configurations {
            get {
                return ((global::System.Collections.Generic.List<TrakHound.Plugins.Client.PluginConfiguration>)(this["Plugin_Configurations"]));
            }
            set {
                this["Plugin_Configurations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Usage_TimesOpened {
            get {
                return ((int)(this["Usage_TimesOpened"]));
            }
            set {
                this["Usage_TimesOpened"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UpdateBehavior {
            get {
                return ((int)(this["UpdateBehavior"]));
            }
            set {
                this["UpdateBehavior"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstOpen {
            get {
                return ((bool)(this["FirstOpen"]));
            }
            set {
                this["FirstOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("initial")]
        public string LastVersion {
            get {
                return ((string)(this["LastVersion"]));
            }
            set {
                this["LastVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginRememberToken {
            get {
                return ((string)(this["LoginRememberToken"]));
            }
            set {
                this["LoginRememberToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DashboardSelectedPage {
            get {
                return ((int)(this["DashboardSelectedPage"]));
            }
            set {
                this["DashboardSelectedPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DashboardIsExpanded {
            get {
                return ((bool)(this["DashboardIsExpanded"]));
            }
            set {
                this["DashboardIsExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int DatabaseReadInterval {
            get {
                return ((int)(this["DatabaseReadInterval"]));
            }
            set {
                this["DatabaseReadInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TableManagerRowDisplayIndex {
            get {
                return ((int)(this["TableManagerRowDisplayIndex"]));
            }
            set {
                this["TableManagerRowDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoBugReport {
            get {
                return ((bool)(this["AutoBugReport"]));
            }
            set {
                this["AutoBugReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public string SavedTheme {
            get {
                return ((string)(this["SavedTheme"]));
            }
            set {
                this["SavedTheme"] = value;
            }
        }
    }
}
